### ISSUE TITLE
IE9 unable to access OAE REST API

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#29]
There is a report (unconfirmed) that IE9 is not able to retrieve data from the OAE's REST API, though it apparently has no problem with DonorsChoose. Needs investigation to see if this is true and, if so, what fixes are available. Note that DonorsChoose uses JSONP while the OAE is pure REST JSON. Also, the OAE API implements CORS; it's not clear how well IE9 deals with CORS.

**Comment by BryanAke** [comment]
IE9 is funky. Might have a solution, although it throws all sorts of security flags and stuff.

I have the OAE API working with the help of a Backbone plugin (https://github.com/victorquinn/Backbone.CrossDomain/). OAE's api only works when loaded via HTTPS, and gives you a redirect when loaded with HTTP, which screws up IE9's CORs implementation no matter what we do, because the right headers aren't attached to the redirect response. 

IE9's XDomainRequest requires that the request goes to a page with the same protocol - so to load OAE's api, we have to load the app via HTTPS.

Loading the page via HTTPS with the backbone plugin as-is throws all sorts of errors, because it also forces the DonorsChoose API to use HTTPS, and it doesn't seem to like that very much. It also flags all the geocoding requests (happening via http, so insecure), and pops up a prompt requiring user permission to show insecure content. 

I hacked around the plugin for DonorsChoose requests specifically and it works after you tell the browser to allow loading insecure content. As far as I can tell, neither the DonorsChoose or Geocoding apis behave with HTTPS, unless there's some other parameters I don't know about that we'd have to give them.

**Comment by sathomas** [comment]
Gonna mark this as wont fix for now. We can resurrect it if IE9 support becomes critical.

**Comment by BryanAke** [comment]
What is the plan for the deployment server? The two solutions I've looked into so far involve either proxying the requests to the OAE api through our server or serving the site via https and sorting out the JSONP apis and any other 'insecure content'. 

All of the other solutions I've found would require either adjustments to the OAE api, or a file hosted there that we can include in an iFrame to proxy requests through. I'm guessing those solutions would be less than ideal?

**Comment by sathomas** [comment]
More questions than answers, I'm afraid. (We still don't know who is going to be responsible for the site once it's launched, much less their technology preferences.) Here's my best guess at the constraints:
- There is no chance of getting the API providers (e.g. ipinfo, donorschoose, or oae) to change their interfaces, so we're stuck with a mix of http and https for API requests.
- In the interim, it is very unlikely (but not completely out of the question) that we'll be able to serve the site using anything other than static pages via http. (Github pages can't serve https, and it would be inefficient to transition away from gh-pages in the short term when we'd have to transition again to the responsible organization, whoever that might be, in a couple of months. Also, no one has been able to tell me the actual domain for the site, which we'd need to get a certificate.)

I'd be interested to hear more about how the iFrame proxy might work. I don't understand it from the description above, but perhaps its workable. Otherwise, the only approach I can think of is to rely on a third-party service like [crossorigin.me](http://crossorigin.me). I wouldn't recommend it for full-on production, but it might be okay as a "proof-of-concept" demonstration for a couple of months (i.e. until the site is transitioned to its eventual owners). Obviously, we'd want to minimize the dependence on a possibly shaky third-party service like this, so we'd only want to invoke it when necessary.

Other ideas and thoughts are most welcome.

**Comment by BryanAke** [comment]
iFrame proxy gets around the CORS issue by loading a page from the remote domain in an iFrame and passing requests through a script on that page - our page passes messages to the iFrame, and since the page in the iFrame is on the same domain as the api, it is exempt from CORS requirements. Unfortunately the page and the proxy script have to be hosted on that domain, so that doesn't work without OAE's help.

I think a 3rd party service like crossorigin.me is the only option we have at the moment - running a proxy on our server would do the same thing without the dependency on a 3rd party and would be more dependable, but that's very dependent on the deployment environment.

I can look into making the call through crossorigin.me when necessary, if that's our best option.

**Comment by sathomas** [comment]
Suggest moving this issue to https://github.com/Georgia-STEM-Incubator/STEM if it's still desirable
