### ISSUE TITLE
Need outline styles for buttons

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#30]
In addition to the current styles for [buttons](https://github.com/sathomas/STEM/blob/rc1/app/styles/btn.less),

![standard](https://cloud.githubusercontent.com/assets/1731910/7009106/f2638100-dc65-11e4-900e-0301bc349d2c.png)

we also need outline styles, e.g.

![outline](https://cloud.githubusercontent.com/assets/1731910/7009118/fefe6614-dc65-11e4-9014-6c960b7db5e3.png)

```
background-color: transparent;
border-width: 2px;
color: @color-theme;
```

Documentation and style guide should be updated appropriately.

**Comment by jcarroll2007** [comment]
Just out of curiosity - why is the class [invite__button](https://github.com/sathomas/STEM/blob/master/app/styles/invite.less#L86) being used to override the button themes? This seams redundant. Since `.btn` already exists, why not use that class?

**Comment by sathomas** [comment]
it's a holdover from the early implementation, and you're right; it shouldn't be needed.

**Comment by jcarroll2007** [comment]
Ok, cool. I'll clean those up.

One other small note - Due to the fact that the standard buttons don't have borders, the height and width of the standard buttons, compared to the transparent buttons, is 4px less (because of the 2px border on each side).

Example: (It's also a bit strange that the transparent button is rendered slightly above the standard one). This image was taken from the updated docs on [my branch](https://github.com/jcarroll2007/STEM/tree/hollow_buttons)
![image](https://cloud.githubusercontent.com/assets/8485105/7051230/cd52b88c-ddf4-11e4-9afe-70dd90051465.png)

Of course, this can be fixed, just let me know if it is important enough to tackle. I briefly tried to add a border to all buttons to keep the size consistent, but this caused other styling issues.

**Comment by sathomas** [comment]
Good to check, and it's definitely not acceptable for the buttons to have different sizes. Seems like it ought to be simple enough to give the default `btn` class a transparent border and then adjust as appropriate for themes. Also looks like the margins and/or padding needs adjustment to vertically center the button text.

**Comment by jcarroll2007** [comment]
OK, I fixed the border and vertically centered issues. Would you like me to remove the `invite__button` class and all other unnecessary classes? (`results-main__button`, `results-secondary__button` etc.)

**Comment by sathomas** [comment]
that would be great

**Comment by sathomas** [comment]
incorporated from PR
