### ISSUE TITLE
Need fallback styling for browsers that don't support flexbox

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#31]
The initial styles make fairly heavy use of flexbox layouts for the [grid](https://github.com/sathomas/STEM/blob/rc1/app/styles/grid.less) and for the [discovery navigation panel](https://github.com/sathomas/STEM/blob/rc1/app/styles/discovery-nav.less). To support IE9, we'll need fallback style rules that don't rely on flexbox. Depending on their complexity, they may need to be incorporated into separate style blocks based on modernizr classes instead of the standard CSS fallback approach. This is especially likely given that the (to be developed) tablet-sized styles are probably going to mess around with flexbox ordering. Best guess is that plain old `float` styles should work for the grid, but the discovery navigation might require `display:table`. It's not essential that the discovery navigation fallbacks are faithful reproductions of the current styles; they only have to provide a reasonable user experience. In addition to the comments within the style sheets, the live [style guide](http://demo.stemincubator.org/docs/styleguide/) for the site may be helpful in explaining how the current styling works.

**Comment by jcarroll2007** [comment]
Looking into this.

**Comment by sathomas** [comment]
Given the results of #29, I'm gonna mark this as wont fix for now. We can resurrect it if IE9 support becomes critical.

**Comment by jcarroll2007** [comment]
I'll start looking into this again.

**Comment by jcarroll2007** [comment]
Discovery nav now works (from what I could tell) exactly as it does in Chrome. I have also added simple float fall-backs for the grid system using `float: left` and `width: X%`.

My solution for the grid system didn't quite feel right, I was worried that setting the width would affect the styling in other browsers, but it didn't seem to. I still think the grid needs more work and a possible re-factor for several reasons.
1. Nested media queries (in less than IE10) are not supported.
2. Due to the way other classes (e.g. [.results-main](https://github.com/sathomas/STEM/blob/master/app/styles/results.less#L51) ) inherit from the grid classes, removing nested media queries or inheriting from modernizr classes like `.flexbox` or `no-flexbox` conflicts with less compilation. 

Creating grid classes that inherit from the modernizr classes sounds optimal

Example:

``` (javascript)
.flexbox .one-column {    
    // styles go here
}

.no-flexbox .one-column {
    // styles go here
}

@media @desktop {
    .one-column { // styles }
    .two-column { // styles }
    // ...
}
```

**Comment by gscoppino** [comment]
I seem to have inherited this work, it lives on the `ie9_fallbacks` branch in my repo which is based off `sathomas/master` and optionally accepts contributions from `jcarroll2007/flexbox_fallbacks`. Various style fixes already done.

Unfortunately, it appears the following do not work on IE9:
- Spotlight isn't showing
- Local partners map has no markers / filters do nothing.
- Certifications map has no markers.

**Comment by gscoppino** [comment]
Ahh, I see issue #29 likely addresses all my issues. Also, should I be reporting fallback styling on issue #51?

**Comment by sathomas** [comment]
Suggest moving this issue to https://github.com/Georgia-STEM-Incubator/STEM if it's still desirable
