### ISSUE TITLE
Alternate responsive designs for tablets and smartphones

### ISSUE THREAD

**Issue by sathomas** [sathomas/STEM#52]
The current design has focussed on desktop viewports with minimal thought given to smartphones and tablets. It's worth looking closely at the responsive design for these alternate viewports to see what improvements can be made.

**Comment by khomotso** [comment]
Is this a note for work you're going to take on yourself? I ask because it's not expressed in a way that really lets anyone else know how to get started or what the requirements are.

**Comment by sathomas** [comment]
This is available for all or anyone to look at. Since it is essentially a design task, there are not specific requirements other than identifying weaknesses in the current design and suggesting improvements.

**Comment by khomotso** [comment]
OK, so IIUC if you're a developer without design expertise, this is probably not an issue you'll want to pick up. Just trying to spell that out for the benefit of Bryan and Jordan trying to parse these issues.

**Comment by jcarroll2007** [comment]
My first impression of using the site on a mobile device is that it is just a bit cramped.
I think that if it functioned a little more like the desktop site, it might be a little more user friendly.
So, instead of all three sections (Resources, Certification and partners) shown at the same time, 
each one could be shown individually and the others hidden (similar to the using the site on a desktop).

A hybrid discovery-nav / landing page approach might fix this issue. 
So, when someone initially visits the site, all articles are hidden and the user might see something like the following:
![image](https://cloud.githubusercontent.com/assets/8485105/7478485/2426c3ee-f329-11e4-9bba-e7faef4aa899.png)

This example only shows the resources section, but certification and partners will be shown similarly and can be accessed by scrolling down the page.
![image](https://cloud.githubusercontent.com/assets/8485105/7478664/2d1a9556-f32a-11e4-9b16-da8ee82b83f3.png)

When the user clicks on one of the links (like the `Resources` button), they will only see information relevant to that section. The menu can be used to navigate between sections.

Single section example view:
![image](https://cloud.githubusercontent.com/assets/8485105/7479532/50858c70-f330-11e4-8b00-88fb8136c55c.png)

**Comment by sathomas** [comment]
Suggest moving this issue to https://github.com/Georgia-STEM-Incubator/STEM if it's still desirable
